FROM golang:1.18-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install -mod=mod github.com/githubnemo/CompileDaemon

CMD  CompileDaemon -build="go build -o main" -command="./main"